### ISSUE TITLE
.

### ISSUE THREAD

**Issue by graysuit** [harborsiem/YouTubeDownloader#5]

**Comment by harborsiem** [comment]
Hello graysuit,

I am not working on this downloader anymore, because Google (Youtube) have done so many changes after the last release of this app. So this program does not work in most cases. But here you can get an other downloader, which works for your Youtube video:

https://github.com/Tyrrrz/YoutubeDownloader

**Comment by graysuit** [comment]
@harborsiem Thanks any way,
Because you worked free of cost for the community and for all of us.
